<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    '361007dbe6037699f54bfca6fef9eb54' => $vendorDir . '/smartling-connector-ralouphie/getallheaders/src/getallheaders.php',
    '4b7ac5f60d97a5cca5146f05bf7df433' => $vendorDir . '/smartling-connector-symfony/polyfill-php72/bootstrap.php',
    '12082faee83422dae6a475ad5f3ea616' => $vendorDir . '/smartling-connector-symfony/polyfill-intl-normalizer/bootstrap.php',
    'fb3fc9a25793455d60080108ee301773' => $vendorDir . '/smartling-connector-guzzlehttp/promises/src/functions_include.php',
    '35cfa758adf5e781c7e88a02fa0f928e' => $vendorDir . '/smartling-connector-guzzlehttp/psr7/src/functions_include.php',
    'cc5991d231fecd7073c1c91559cbf7c2' => $vendorDir . '/smartling-connector-symfony/polyfill-intl-idn/bootstrap.php',
    '9bd41e9b234e34d04068e933d9716d0e' => $vendorDir . '/smartling-connector-symfony/polyfill-ctype/bootstrap.php',
    'a144be3cc862d7f9a80b5f1d2f7dd0bc' => $vendorDir . '/smartling-connector-guzzlehttp/guzzle/src/functions_include.php',
    '43ffb623e97f39feae57e52e1fbae69d' => $vendorDir . '/smartling-connector-jralph/retry/src/helper.php',
);
