<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Smartling\\Vendor\\Utilities\\' => array($vendorDir . '/smartling-connector-galbar/jsonpath/src/Galbar/Utilities'),
    'Smartling\\Vendor\\Symfony\\Polyfill\\Php72\\' => array($vendorDir . '/smartling-connector-symfony/polyfill-php72'),
    'Smartling\\Vendor\\Symfony\\Polyfill\\Intl\\Normalizer\\' => array($vendorDir . '/smartling-connector-symfony/polyfill-intl-normalizer'),
    'Smartling\\Vendor\\Symfony\\Polyfill\\Intl\\Idn\\' => array($vendorDir . '/smartling-connector-symfony/polyfill-intl-idn'),
    'Smartling\\Vendor\\Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/smartling-connector-symfony/polyfill-ctype'),
    'Smartling\\Vendor\\Symfony\\Component\\Yaml\\' => array($vendorDir . '/smartling-connector-symfony/yaml'),
    'Smartling\\Vendor\\Symfony\\Component\\Filesystem\\' => array($vendorDir . '/smartling-connector-symfony/filesystem'),
    'Smartling\\Vendor\\Symfony\\Component\\DependencyInjection\\' => array($vendorDir . '/smartling-connector-symfony/dependency-injection'),
    'Smartling\\Vendor\\Symfony\\Component\\Config\\' => array($vendorDir . '/smartling-connector-symfony/config'),
    'Smartling\\Vendor\\Smartling\\' => array($vendorDir . '/smartling-connector-smartling/api-sdk-php/src'),
    'Smartling\\Vendor\\Psr\\Log\\' => array($vendorDir . '/smartling-connector-psr/log/Psr/Log'),
    'Smartling\\Vendor\\Psr\\Http\\Message\\' => array($vendorDir . '/smartling-connector-psr/http-message/src'),
    'Smartling\\Vendor\\Monolog\\' => array($vendorDir . '/smartling-connector-monolog/monolog/src/Monolog'),
    'Smartling\\Vendor\\JsonPath\\' => array($vendorDir . '/smartling-connector-galbar/jsonpath/src/Galbar/JsonPath'),
    'Smartling\\Vendor\\Jralph\\Retry\\' => array($vendorDir . '/smartling-connector-jralph/retry/src'),
    'Smartling\\Vendor\\GuzzleHttp\\Psr7\\' => array($vendorDir . '/smartling-connector-guzzlehttp/psr7/src'),
    'Smartling\\Vendor\\GuzzleHttp\\Promise\\' => array($vendorDir . '/smartling-connector-guzzlehttp/promises/src'),
    'Smartling\\Vendor\\GuzzleHttp\\' => array($vendorDir . '/smartling-connector-guzzlehttp/guzzle/src'),
);
