<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1bc698622a97e2209782545261fe1b0a
{
    public static $files = array (
        '361007dbe6037699f54bfca6fef9eb54' => __DIR__ . '/..' . '/smartling-connector-ralouphie/getallheaders/src/getallheaders.php',
        '4b7ac5f60d97a5cca5146f05bf7df433' => __DIR__ . '/..' . '/smartling-connector-symfony/polyfill-php72/bootstrap.php',
        '12082faee83422dae6a475ad5f3ea616' => __DIR__ . '/..' . '/smartling-connector-symfony/polyfill-intl-normalizer/bootstrap.php',
        'fb3fc9a25793455d60080108ee301773' => __DIR__ . '/..' . '/smartling-connector-guzzlehttp/promises/src/functions_include.php',
        '35cfa758adf5e781c7e88a02fa0f928e' => __DIR__ . '/..' . '/smartling-connector-guzzlehttp/psr7/src/functions_include.php',
        'cc5991d231fecd7073c1c91559cbf7c2' => __DIR__ . '/..' . '/smartling-connector-symfony/polyfill-intl-idn/bootstrap.php',
        '9bd41e9b234e34d04068e933d9716d0e' => __DIR__ . '/..' . '/smartling-connector-symfony/polyfill-ctype/bootstrap.php',
        'a144be3cc862d7f9a80b5f1d2f7dd0bc' => __DIR__ . '/..' . '/smartling-connector-guzzlehttp/guzzle/src/functions_include.php',
        '43ffb623e97f39feae57e52e1fbae69d' => __DIR__ . '/..' . '/smartling-connector-jralph/retry/src/helper.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Smartling\\Vendor\\Utilities\\' => 27,
            'Smartling\\Vendor\\Symfony\\Polyfill\\Php72\\' => 40,
            'Smartling\\Vendor\\Symfony\\Polyfill\\Intl\\Normalizer\\' => 50,
            'Smartling\\Vendor\\Symfony\\Polyfill\\Intl\\Idn\\' => 43,
            'Smartling\\Vendor\\Symfony\\Polyfill\\Ctype\\' => 40,
            'Smartling\\Vendor\\Symfony\\Component\\Yaml\\' => 40,
            'Smartling\\Vendor\\Symfony\\Component\\Filesystem\\' => 46,
            'Smartling\\Vendor\\Symfony\\Component\\DependencyInjection\\' => 55,
            'Smartling\\Vendor\\Symfony\\Component\\Config\\' => 42,
            'Smartling\\Vendor\\Smartling\\' => 27,
            'Smartling\\Vendor\\Psr\\Log\\' => 25,
            'Smartling\\Vendor\\Psr\\Http\\Message\\' => 34,
            'Smartling\\Vendor\\Monolog\\' => 25,
            'Smartling\\Vendor\\JsonPath\\' => 26,
            'Smartling\\Vendor\\Jralph\\Retry\\' => 30,
            'Smartling\\Vendor\\GuzzleHttp\\Psr7\\' => 33,
            'Smartling\\Vendor\\GuzzleHttp\\Promise\\' => 36,
            'Smartling\\Vendor\\GuzzleHttp\\' => 28,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Smartling\\Vendor\\Utilities\\' => 
        array (
            0 => __DIR__ . '/..' . '/smartling-connector-galbar/jsonpath/src/Galbar/Utilities',
        ),
        'Smartling\\Vendor\\Symfony\\Polyfill\\Php72\\' => 
        array (
            0 => __DIR__ . '/..' . '/smartling-connector-symfony/polyfill-php72',
        ),
        'Smartling\\Vendor\\Symfony\\Polyfill\\Intl\\Normalizer\\' => 
        array (
            0 => __DIR__ . '/..' . '/smartling-connector-symfony/polyfill-intl-normalizer',
        ),
        'Smartling\\Vendor\\Symfony\\Polyfill\\Intl\\Idn\\' => 
        array (
            0 => __DIR__ . '/..' . '/smartling-connector-symfony/polyfill-intl-idn',
        ),
        'Smartling\\Vendor\\Symfony\\Polyfill\\Ctype\\' => 
        array (
            0 => __DIR__ . '/..' . '/smartling-connector-symfony/polyfill-ctype',
        ),
        'Smartling\\Vendor\\Symfony\\Component\\Yaml\\' => 
        array (
            0 => __DIR__ . '/..' . '/smartling-connector-symfony/yaml',
        ),
        'Smartling\\Vendor\\Symfony\\Component\\Filesystem\\' => 
        array (
            0 => __DIR__ . '/..' . '/smartling-connector-symfony/filesystem',
        ),
        'Smartling\\Vendor\\Symfony\\Component\\DependencyInjection\\' => 
        array (
            0 => __DIR__ . '/..' . '/smartling-connector-symfony/dependency-injection',
        ),
        'Smartling\\Vendor\\Symfony\\Component\\Config\\' => 
        array (
            0 => __DIR__ . '/..' . '/smartling-connector-symfony/config',
        ),
        'Smartling\\Vendor\\Smartling\\' => 
        array (
            0 => __DIR__ . '/..' . '/smartling-connector-smartling/api-sdk-php/src',
        ),
        'Smartling\\Vendor\\Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/smartling-connector-psr/log/Psr/Log',
        ),
        'Smartling\\Vendor\\Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/smartling-connector-psr/http-message/src',
        ),
        'Smartling\\Vendor\\Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/smartling-connector-monolog/monolog/src/Monolog',
        ),
        'Smartling\\Vendor\\JsonPath\\' => 
        array (
            0 => __DIR__ . '/..' . '/smartling-connector-galbar/jsonpath/src/Galbar/JsonPath',
        ),
        'Smartling\\Vendor\\Jralph\\Retry\\' => 
        array (
            0 => __DIR__ . '/..' . '/smartling-connector-jralph/retry/src',
        ),
        'Smartling\\Vendor\\GuzzleHttp\\Psr7\\' => 
        array (
            0 => __DIR__ . '/..' . '/smartling-connector-guzzlehttp/psr7/src',
        ),
        'Smartling\\Vendor\\GuzzleHttp\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/smartling-connector-guzzlehttp/promises/src',
        ),
        'Smartling\\Vendor\\GuzzleHttp\\' => 
        array (
            0 => __DIR__ . '/..' . '/smartling-connector-guzzlehttp/guzzle/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'S' => 
        array (
            'Smartling' => 
            array (
                0 => __DIR__ . '/../../..' . '/inc',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Normalizer' => __DIR__ . '/..' . '/smartling-connector-symfony/polyfill-intl-normalizer/Resources/stubs/Normalizer.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1bc698622a97e2209782545261fe1b0a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1bc698622a97e2209782545261fe1b0a::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit1bc698622a97e2209782545261fe1b0a::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit1bc698622a97e2209782545261fe1b0a::$classMap;

        }, null, ClassLoader::class);
    }
}
