<?php return array(
    'root' => array(
        'pretty_version' => '2.12.3',
        'version' => '2.12.3.0',
        'type' => 'wordpress-plugin',
        'install_path' => __DIR__ . '/../../../',
        'aliases' => array(),
        'reference' => NULL,
        'name' => 'smartling/wordpress-connector',
        'dev' => false,
    ),
    'versions' => array(
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0',
            ),
        ),
        'smartling-connector-galbar/jsonpath' => array(
            'pretty_version' => '2.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smartling-connector-galbar/jsonpath',
            'aliases' => array(),
            'reference' => 'a71634349df6b696af16032a047f57908b5cc1eb',
            'dev_requirement' => false,
        ),
        'smartling-connector-guzzlehttp/guzzle' => array(
            'pretty_version' => '6.5.5',
            'version' => '6.5.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smartling-connector-guzzlehttp/guzzle',
            'aliases' => array(),
            'reference' => 'a389bf84aeb5a0e77ebb62d91d9df72e2172ce92',
            'dev_requirement' => false,
        ),
        'smartling-connector-guzzlehttp/promises' => array(
            'pretty_version' => '1.5.1',
            'version' => '1.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smartling-connector-guzzlehttp/promises',
            'aliases' => array(),
            'reference' => '9cd414d6119039463c43fc29e44d87714eb01408',
            'dev_requirement' => false,
        ),
        'smartling-connector-guzzlehttp/psr7' => array(
            'pretty_version' => '1.8.5',
            'version' => '1.8.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smartling-connector-guzzlehttp/psr7',
            'aliases' => array(),
            'reference' => 'd2cbaa29eb0b1e152b5cba532826dd905f2424e2',
            'dev_requirement' => false,
        ),
        'smartling-connector-jralph/retry' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smartling-connector-jralph/retry',
            'aliases' => array(),
            'reference' => 'e425e5ffa5cdffe36cf3641ea374e7cee80fc289',
            'dev_requirement' => false,
        ),
        'smartling-connector-monolog/monolog' => array(
            'pretty_version' => '1.27.0',
            'version' => '1.27.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smartling-connector-monolog/monolog',
            'aliases' => array(),
            'reference' => '62c065a829cc45e5d291a172a1a82aae6b1331b9',
            'dev_requirement' => false,
        ),
        'smartling-connector-psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smartling-connector-psr/http-message',
            'aliases' => array(),
            'reference' => 'aaaae05b517dfceb9eaef820b7e2b4d42ba67b9a',
            'dev_requirement' => false,
        ),
        'smartling-connector-psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smartling-connector-psr/log',
            'aliases' => array(),
            'reference' => '1b2d8782974e296d4ef5e0d848acc2ec15d6f45c',
            'dev_requirement' => false,
        ),
        'smartling-connector-ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smartling-connector-ralouphie/getallheaders',
            'aliases' => array(),
            'reference' => '09acae6f537cb8b574acfad5eca90f6da36a4e66',
            'dev_requirement' => false,
        ),
        'smartling-connector-smartling/api-sdk-php' => array(
            'pretty_version' => '3.9.2',
            'version' => '3.9.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smartling-connector-smartling/api-sdk-php',
            'aliases' => array(),
            'reference' => '9ed480d90734d6a218c77e5e735f48870fb5410d',
            'dev_requirement' => false,
        ),
        'smartling-connector-symfony/config' => array(
            'pretty_version' => 'v2.8.52',
            'version' => '2.8.52.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smartling-connector-symfony/config',
            'aliases' => array(),
            'reference' => '9f08fe7ddbed73fafabfc894efbdc9aab4922087',
            'dev_requirement' => false,
        ),
        'smartling-connector-symfony/dependency-injection' => array(
            'pretty_version' => 'v2.8.52',
            'version' => '2.8.52.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smartling-connector-symfony/dependency-injection',
            'aliases' => array(),
            'reference' => '879e7c00776d4acb94af8a84ab32651524f44015',
            'dev_requirement' => false,
        ),
        'smartling-connector-symfony/filesystem' => array(
            'pretty_version' => 'v3.0.9',
            'version' => '3.0.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smartling-connector-symfony/filesystem',
            'aliases' => array(),
            'reference' => 'dd446a360a539a127e44b3aeb44238e6e4c7f5b0',
            'dev_requirement' => false,
        ),
        'smartling-connector-symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smartling-connector-symfony/polyfill-ctype',
            'aliases' => array(),
            'reference' => '787d6322dd05ba3e63b4f3b86ae234a5fd287b04',
            'dev_requirement' => false,
        ),
        'smartling-connector-symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smartling-connector-symfony/polyfill-intl-idn',
            'aliases' => array(),
            'reference' => '257a09014d294a7e26f3630d41bdf929db4bff32',
            'dev_requirement' => false,
        ),
        'smartling-connector-symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smartling-connector-symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'reference' => '1b20d7ab57e7851768507562f9f7e60006c9e6b1',
            'dev_requirement' => false,
        ),
        'smartling-connector-symfony/polyfill-php72' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smartling-connector-symfony/polyfill-php72',
            'aliases' => array(),
            'reference' => 'd05886e1cfa4f1fecd459f808c5b69cc070e7c71',
            'dev_requirement' => false,
        ),
        'smartling-connector-symfony/yaml' => array(
            'pretty_version' => 'v2.8.52',
            'version' => '2.8.52.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smartling-connector-symfony/yaml',
            'aliases' => array(),
            'reference' => '41987e62858442dac4ef490bb7b0d0ed1a063a25',
            'dev_requirement' => false,
        ),
        'smartling/wordpress-connector' => array(
            'pretty_version' => '2.12.3',
            'version' => '2.12.3.0',
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../../../',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
    ),
);
